default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8 .
        language: system
        types: [python]
